name: Run .NET Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.301' # Replace with your exact version if needed

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --no-restore

    - name: Run unit tests
      run: dotnet test ./CharacterManagerApiTutorial.Tests/CharacterManagerApiTutorial.Tests.csproj --no-build --verbosity normal